### PR TITLE
Update Pipfile.lock

### PR DESCRIPTION
**Pull request by natsukium**
Fix Travis CI's error.

### CODE REVIEW

**Comment by yamasakih** [comment]
@natsukium  
Thx :) Did the error raise because Pipfile.lock have not been updated?

**Comment by natsukium** [comment]
Yes.
Please update a Pipfile.lock when you change a Pipfile.

**Comment by yamasakih** [comment]
Brilliant!! 💎

**Comment by yamasakih** [comment]
@natsukium Brilliant!! 💎Thank you :)

**Pull request merged**
